name: Build and push KinD node image

on:
  push:
    tags:
      - 'v1.2[0-9].[0-9]+'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set tag to use in environment
        run: |-
          echo "TAG=$(
          if [ -n "${{ github.event.inputs.tag }}" ]; then
            echo ${{ github.event.inputs.tag }}
          else
            echo ${{ github.ref }}
          fi
          )" >> $GITHUB_ENV
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          ref: ${{ env.TAG }}
      - name: Install KinD
        uses: helm/kind-action@v1.3.0
        with:
          install_only: true
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build KinD image for amd64
        run: |
          kind build node-image . --arch amd64 --image jimmidyson/kind-node:${{ env.TAG }}-amd64
      - name: Build KinD image for arm64
        run: |
          kind build node-image . --arch arm64 --image jimmidyson/kind-node:${{ env.TAG }}-arm64
      - name: Push KinD images
        run: |
          docker push jimmidyson/kind-node:${{ env.TAG }}-amd64
          docker push jimmidyson/kind-node:${{ env.TAG }}-arm64
      - name: Push KinD multiplatform manifest
        run: |
          docker manifest create jimmidyson/kind-node:${{ env.TAG }}{,-{arm64,amd64}}
          docker manifest push jimmidyson/kind-node:${{ env.TAG }}
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
