name: Build and push KinD node image

on:
  push:
    tags:
      - 'v1.2[0-9].[0-9]+'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to build images for'
        required: true

jobs:
  build-and-push-arch-images:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        arch: [amd64, arm64]

    steps:
      - name: Set tag to use in environment
        run: |-
          echo "TAG=$(
          if [ -n "${{ github.event.inputs.tag }}" ]; then
            echo ${{ github.event.inputs.tag }}
          else
            echo ${{ github.ref }}
          fi
          )" >> $GITHUB_ENV
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          ref: ${{ env.TAG }}
      - name: Install KinD
        uses: helm/kind-action@v1.3.0
        with:
          install_only: true
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Build KinD image for ${{ matrix.arch }}
        run: |
          kind build node-image . --arch ${{ matrix.arch }} --image ${{ github.repository_owner }}/kind-node:${{ env.TAG }}-${{ matrix.arch }}
      - name: Push KinD images
        run: |
          docker push ${{ github.repository_owner }}/kind-node:${{ env.TAG }}-${{ matrix.arch }}

  build-and-push-manifest:
    needs: [build-and-push-arch-images]

    runs-on: ubuntu-latest

    steps:
      - name: Set tag to use in environment
        run: |-
          echo "TAG=$(
          if [ -n "${{ github.event.inputs.tag }}" ]; then
            echo ${{ github.event.inputs.tag }}
          else
            echo ${{ github.ref }}
          fi
          )" >> $GITHUB_ENV
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Push KinD multiplatform manifest
        run: |
          docker manifest create ${{ github.repository_owner }}/kind-node:${{ env.TAG }}{,-{arm64,amd64}}
          docker manifest push ${{ github.repository_owner }}/kind-node:${{ env.TAG }}
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
