name: Build and push KinD node image

on:
  push:
    tags:
      - 'v1.2[0-9].[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Install KinD
        uses: helm/kind-action@v1.3.0
        with:
          install_only: true
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build KinD image for amd64
        run: |
          kind build node-image . --arch amd64 --image jimmidyson/kind-node:${{github.ref}}-amd64
      - name: Build KinD image for arm64
        run: |
          kind build node-image . --arch arm64 --image jimmidyson/kind-node:${{github.ref}}-arm64
      - name: Push KinD images
        run: |
          docker push jimmidyson/kind-node:${{github.ref}}-amd64
          docker push jimmidyson/kind-node:${{github.ref}}-arm64
      - name: Push KinD multiplatform manifest
        run: |
          docker manifest create jimmidyson/kind-node:${{github.ref}}{,-{arm64,amd64}}
          docker manifest push jimmidyson/kind-node:${{github.ref}}
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
