name: Sync Kubernetes repository tags

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  git-sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: git-sync-k8s-tags
        uses: wei/git-sync@v3
        with:
          source_repo: "https://github.com/kubernetes/kubernetes.git"
          source_branch: "refs/tags/*"
          destination_repo: "git@github.com:${{github.repository}}.git"
          destination_branch: "refs/tags/*"
          destination_ssh_private_key: ${{ secrets.DESTINATION_SSH_PRIVATE_KEY }}
