name: Sync Kubernetes repository tags

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch: # And manually on button click.

jobs:
  git-sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: git-sync-k8s-tags
        uses: wei/git-sync@v3
        with:
          source_repo: "https://github.com/kubernetes/kubernetes.git"
          source_branch: "refs/tags/*"
          destination_repo: "https://x-access-token:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git"
          destination_branch: "refs/tags/*"
